[package]
name = "code_gen"
version = "0.1.0"
edition = "2024"

[dependencies]
paste = "1.0"
code_gen_macro = { path = "../code_gen_macro" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.5", features = ["derive"] }
maud = "0.26"
